// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fractal.proto

#include "fractal.pb.h"
#include "fractal.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace fractal {

static const char* FractalService_method_names[] = {
  "/fractal.FractalService/CalculateJulia",
};

std::unique_ptr< FractalService::Stub> FractalService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FractalService::Stub> stub(new FractalService::Stub(channel, options));
  return stub;
}

FractalService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculateJulia_(FractalService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FractalService::Stub::CalculateJulia(::grpc::ClientContext* context, const ::fractal::JuliaRequest& request, ::fractal::JuliaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fractal::JuliaRequest, ::fractal::JuliaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateJulia_, context, request, response);
}

void FractalService::Stub::async::CalculateJulia(::grpc::ClientContext* context, const ::fractal::JuliaRequest* request, ::fractal::JuliaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fractal::JuliaRequest, ::fractal::JuliaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateJulia_, context, request, response, std::move(f));
}

void FractalService::Stub::async::CalculateJulia(::grpc::ClientContext* context, const ::fractal::JuliaRequest* request, ::fractal::JuliaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateJulia_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fractal::JuliaResponse>* FractalService::Stub::PrepareAsyncCalculateJuliaRaw(::grpc::ClientContext* context, const ::fractal::JuliaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fractal::JuliaResponse, ::fractal::JuliaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateJulia_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fractal::JuliaResponse>* FractalService::Stub::AsyncCalculateJuliaRaw(::grpc::ClientContext* context, const ::fractal::JuliaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateJuliaRaw(context, request, cq);
  result->StartCall();
  return result;
}

FractalService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FractalService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FractalService::Service, ::fractal::JuliaRequest, ::fractal::JuliaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FractalService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fractal::JuliaRequest* req,
             ::fractal::JuliaResponse* resp) {
               return service->CalculateJulia(ctx, req, resp);
             }, this)));
}

FractalService::Service::~Service() {
}

::grpc::Status FractalService::Service::CalculateJulia(::grpc::ServerContext* context, const ::fractal::JuliaRequest* request, ::fractal::JuliaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fractal

