// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fractal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fractal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_fractal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fractal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fractal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fractal_2eproto;
namespace fractal {
class JuliaRequest;
struct JuliaRequestDefaultTypeInternal;
extern JuliaRequestDefaultTypeInternal _JuliaRequest_default_instance_;
class JuliaResponse;
struct JuliaResponseDefaultTypeInternal;
extern JuliaResponseDefaultTypeInternal _JuliaResponse_default_instance_;
class ShutdownRequest;
struct ShutdownRequestDefaultTypeInternal;
extern ShutdownRequestDefaultTypeInternal _ShutdownRequest_default_instance_;
class ShutdownResponse;
struct ShutdownResponseDefaultTypeInternal;
extern ShutdownResponseDefaultTypeInternal _ShutdownResponse_default_instance_;
}  // namespace fractal
PROTOBUF_NAMESPACE_OPEN
template<> ::fractal::JuliaRequest* Arena::CreateMaybeMessage<::fractal::JuliaRequest>(Arena*);
template<> ::fractal::JuliaResponse* Arena::CreateMaybeMessage<::fractal::JuliaResponse>(Arena*);
template<> ::fractal::ShutdownRequest* Arena::CreateMaybeMessage<::fractal::ShutdownRequest>(Arena*);
template<> ::fractal::ShutdownResponse* Arena::CreateMaybeMessage<::fractal::ShutdownResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fractal {

// ===================================================================

class JuliaRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fractal.JuliaRequest) */ {
 public:
  inline JuliaRequest() : JuliaRequest(nullptr) {}
  ~JuliaRequest() override;
  explicit PROTOBUF_CONSTEXPR JuliaRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JuliaRequest(const JuliaRequest& from);
  JuliaRequest(JuliaRequest&& from) noexcept
    : JuliaRequest() {
    *this = ::std::move(from);
  }

  inline JuliaRequest& operator=(const JuliaRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline JuliaRequest& operator=(JuliaRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JuliaRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const JuliaRequest* internal_default_instance() {
    return reinterpret_cast<const JuliaRequest*>(
               &_JuliaRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JuliaRequest& a, JuliaRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(JuliaRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JuliaRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JuliaRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JuliaRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JuliaRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JuliaRequest& from) {
    JuliaRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JuliaRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fractal.JuliaRequest";
  }
  protected:
  explicit JuliaRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCRealFieldNumber = 1,
    kCImagFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
    kMaxIterationsFieldNumber = 5,
    kPolyDegreeFieldNumber = 6,
    kXMinFieldNumber = 7,
    kXMaxFieldNumber = 8,
    kYMinFieldNumber = 9,
    kYMaxFieldNumber = 10,
  };
  // double c_real = 1;
  void clear_c_real();
  double c_real() const;
  void set_c_real(double value);
  private:
  double _internal_c_real() const;
  void _internal_set_c_real(double value);
  public:

  // double c_imag = 2;
  void clear_c_imag();
  double c_imag() const;
  void set_c_imag(double value);
  private:
  double _internal_c_imag() const;
  void _internal_set_c_imag(double value);
  public:

  // int32 width = 3;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 4;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // int32 max_iterations = 5;
  void clear_max_iterations();
  int32_t max_iterations() const;
  void set_max_iterations(int32_t value);
  private:
  int32_t _internal_max_iterations() const;
  void _internal_set_max_iterations(int32_t value);
  public:

  // int32 poly_degree = 6;
  void clear_poly_degree();
  int32_t poly_degree() const;
  void set_poly_degree(int32_t value);
  private:
  int32_t _internal_poly_degree() const;
  void _internal_set_poly_degree(int32_t value);
  public:

  // double x_min = 7;
  void clear_x_min();
  double x_min() const;
  void set_x_min(double value);
  private:
  double _internal_x_min() const;
  void _internal_set_x_min(double value);
  public:

  // double x_max = 8;
  void clear_x_max();
  double x_max() const;
  void set_x_max(double value);
  private:
  double _internal_x_max() const;
  void _internal_set_x_max(double value);
  public:

  // double y_min = 9;
  void clear_y_min();
  double y_min() const;
  void set_y_min(double value);
  private:
  double _internal_y_min() const;
  void _internal_set_y_min(double value);
  public:

  // double y_max = 10;
  void clear_y_max();
  double y_max() const;
  void set_y_max(double value);
  private:
  double _internal_y_max() const;
  void _internal_set_y_max(double value);
  public:

  // @@protoc_insertion_point(class_scope:fractal.JuliaRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double c_real_;
    double c_imag_;
    int32_t width_;
    int32_t height_;
    int32_t max_iterations_;
    int32_t poly_degree_;
    double x_min_;
    double x_max_;
    double y_min_;
    double y_max_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class JuliaResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fractal.JuliaResponse) */ {
 public:
  inline JuliaResponse() : JuliaResponse(nullptr) {}
  ~JuliaResponse() override;
  explicit PROTOBUF_CONSTEXPR JuliaResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JuliaResponse(const JuliaResponse& from);
  JuliaResponse(JuliaResponse&& from) noexcept
    : JuliaResponse() {
    *this = ::std::move(from);
  }

  inline JuliaResponse& operator=(const JuliaResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline JuliaResponse& operator=(JuliaResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JuliaResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const JuliaResponse* internal_default_instance() {
    return reinterpret_cast<const JuliaResponse*>(
               &_JuliaResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(JuliaResponse& a, JuliaResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(JuliaResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JuliaResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JuliaResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JuliaResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JuliaResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JuliaResponse& from) {
    JuliaResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JuliaResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fractal.JuliaResponse";
  }
  protected:
  explicit JuliaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRgbaDataFieldNumber = 1,
    kServerIdFieldNumber = 3,
    kCalculationTimeMsFieldNumber = 2,
  };
  // bytes rgba_data = 1;
  void clear_rgba_data();
  const std::string& rgba_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rgba_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rgba_data();
  PROTOBUF_NODISCARD std::string* release_rgba_data();
  void set_allocated_rgba_data(std::string* rgba_data);
  private:
  const std::string& _internal_rgba_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rgba_data(const std::string& value);
  std::string* _internal_mutable_rgba_data();
  public:

  // string server_id = 3;
  void clear_server_id();
  const std::string& server_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_id();
  PROTOBUF_NODISCARD std::string* release_server_id();
  void set_allocated_server_id(std::string* server_id);
  private:
  const std::string& _internal_server_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_id(const std::string& value);
  std::string* _internal_mutable_server_id();
  public:

  // double calculation_time_ms = 2;
  void clear_calculation_time_ms();
  double calculation_time_ms() const;
  void set_calculation_time_ms(double value);
  private:
  double _internal_calculation_time_ms() const;
  void _internal_set_calculation_time_ms(double value);
  public:

  // @@protoc_insertion_point(class_scope:fractal.JuliaResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rgba_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_id_;
    double calculation_time_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class ShutdownRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:fractal.ShutdownRequest) */ {
 public:
  inline ShutdownRequest() : ShutdownRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR ShutdownRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShutdownRequest(const ShutdownRequest& from);
  ShutdownRequest(ShutdownRequest&& from) noexcept
    : ShutdownRequest() {
    *this = ::std::move(from);
  }

  inline ShutdownRequest& operator=(const ShutdownRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShutdownRequest& operator=(ShutdownRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShutdownRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShutdownRequest* internal_default_instance() {
    return reinterpret_cast<const ShutdownRequest*>(
               &_ShutdownRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ShutdownRequest& a, ShutdownRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ShutdownRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShutdownRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShutdownRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShutdownRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ShutdownRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ShutdownRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fractal.ShutdownRequest";
  }
  protected:
  explicit ShutdownRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:fractal.ShutdownRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_fractal_2eproto;
};
// -------------------------------------------------------------------

class ShutdownResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fractal.ShutdownResponse) */ {
 public:
  inline ShutdownResponse() : ShutdownResponse(nullptr) {}
  ~ShutdownResponse() override;
  explicit PROTOBUF_CONSTEXPR ShutdownResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShutdownResponse(const ShutdownResponse& from);
  ShutdownResponse(ShutdownResponse&& from) noexcept
    : ShutdownResponse() {
    *this = ::std::move(from);
  }

  inline ShutdownResponse& operator=(const ShutdownResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShutdownResponse& operator=(ShutdownResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShutdownResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShutdownResponse* internal_default_instance() {
    return reinterpret_cast<const ShutdownResponse*>(
               &_ShutdownResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ShutdownResponse& a, ShutdownResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ShutdownResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShutdownResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShutdownResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShutdownResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShutdownResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShutdownResponse& from) {
    ShutdownResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShutdownResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fractal.ShutdownResponse";
  }
  protected:
  explicit ShutdownResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:fractal.ShutdownResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fractal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JuliaRequest

// double c_real = 1;
inline void JuliaRequest::clear_c_real() {
  _impl_.c_real_ = 0;
}
inline double JuliaRequest::_internal_c_real() const {
  return _impl_.c_real_;
}
inline double JuliaRequest::c_real() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.c_real)
  return _internal_c_real();
}
inline void JuliaRequest::_internal_set_c_real(double value) {
  
  _impl_.c_real_ = value;
}
inline void JuliaRequest::set_c_real(double value) {
  _internal_set_c_real(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.c_real)
}

// double c_imag = 2;
inline void JuliaRequest::clear_c_imag() {
  _impl_.c_imag_ = 0;
}
inline double JuliaRequest::_internal_c_imag() const {
  return _impl_.c_imag_;
}
inline double JuliaRequest::c_imag() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.c_imag)
  return _internal_c_imag();
}
inline void JuliaRequest::_internal_set_c_imag(double value) {
  
  _impl_.c_imag_ = value;
}
inline void JuliaRequest::set_c_imag(double value) {
  _internal_set_c_imag(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.c_imag)
}

// int32 width = 3;
inline void JuliaRequest::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t JuliaRequest::_internal_width() const {
  return _impl_.width_;
}
inline int32_t JuliaRequest::width() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.width)
  return _internal_width();
}
inline void JuliaRequest::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void JuliaRequest::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.width)
}

// int32 height = 4;
inline void JuliaRequest::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t JuliaRequest::_internal_height() const {
  return _impl_.height_;
}
inline int32_t JuliaRequest::height() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.height)
  return _internal_height();
}
inline void JuliaRequest::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void JuliaRequest::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.height)
}

// int32 max_iterations = 5;
inline void JuliaRequest::clear_max_iterations() {
  _impl_.max_iterations_ = 0;
}
inline int32_t JuliaRequest::_internal_max_iterations() const {
  return _impl_.max_iterations_;
}
inline int32_t JuliaRequest::max_iterations() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.max_iterations)
  return _internal_max_iterations();
}
inline void JuliaRequest::_internal_set_max_iterations(int32_t value) {
  
  _impl_.max_iterations_ = value;
}
inline void JuliaRequest::set_max_iterations(int32_t value) {
  _internal_set_max_iterations(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.max_iterations)
}

// int32 poly_degree = 6;
inline void JuliaRequest::clear_poly_degree() {
  _impl_.poly_degree_ = 0;
}
inline int32_t JuliaRequest::_internal_poly_degree() const {
  return _impl_.poly_degree_;
}
inline int32_t JuliaRequest::poly_degree() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.poly_degree)
  return _internal_poly_degree();
}
inline void JuliaRequest::_internal_set_poly_degree(int32_t value) {
  
  _impl_.poly_degree_ = value;
}
inline void JuliaRequest::set_poly_degree(int32_t value) {
  _internal_set_poly_degree(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.poly_degree)
}

// double x_min = 7;
inline void JuliaRequest::clear_x_min() {
  _impl_.x_min_ = 0;
}
inline double JuliaRequest::_internal_x_min() const {
  return _impl_.x_min_;
}
inline double JuliaRequest::x_min() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.x_min)
  return _internal_x_min();
}
inline void JuliaRequest::_internal_set_x_min(double value) {
  
  _impl_.x_min_ = value;
}
inline void JuliaRequest::set_x_min(double value) {
  _internal_set_x_min(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.x_min)
}

// double x_max = 8;
inline void JuliaRequest::clear_x_max() {
  _impl_.x_max_ = 0;
}
inline double JuliaRequest::_internal_x_max() const {
  return _impl_.x_max_;
}
inline double JuliaRequest::x_max() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.x_max)
  return _internal_x_max();
}
inline void JuliaRequest::_internal_set_x_max(double value) {
  
  _impl_.x_max_ = value;
}
inline void JuliaRequest::set_x_max(double value) {
  _internal_set_x_max(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.x_max)
}

// double y_min = 9;
inline void JuliaRequest::clear_y_min() {
  _impl_.y_min_ = 0;
}
inline double JuliaRequest::_internal_y_min() const {
  return _impl_.y_min_;
}
inline double JuliaRequest::y_min() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.y_min)
  return _internal_y_min();
}
inline void JuliaRequest::_internal_set_y_min(double value) {
  
  _impl_.y_min_ = value;
}
inline void JuliaRequest::set_y_min(double value) {
  _internal_set_y_min(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.y_min)
}

// double y_max = 10;
inline void JuliaRequest::clear_y_max() {
  _impl_.y_max_ = 0;
}
inline double JuliaRequest::_internal_y_max() const {
  return _impl_.y_max_;
}
inline double JuliaRequest::y_max() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaRequest.y_max)
  return _internal_y_max();
}
inline void JuliaRequest::_internal_set_y_max(double value) {
  
  _impl_.y_max_ = value;
}
inline void JuliaRequest::set_y_max(double value) {
  _internal_set_y_max(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaRequest.y_max)
}

// -------------------------------------------------------------------

// JuliaResponse

// bytes rgba_data = 1;
inline void JuliaResponse::clear_rgba_data() {
  _impl_.rgba_data_.ClearToEmpty();
}
inline const std::string& JuliaResponse::rgba_data() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaResponse.rgba_data)
  return _internal_rgba_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JuliaResponse::set_rgba_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rgba_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fractal.JuliaResponse.rgba_data)
}
inline std::string* JuliaResponse::mutable_rgba_data() {
  std::string* _s = _internal_mutable_rgba_data();
  // @@protoc_insertion_point(field_mutable:fractal.JuliaResponse.rgba_data)
  return _s;
}
inline const std::string& JuliaResponse::_internal_rgba_data() const {
  return _impl_.rgba_data_.Get();
}
inline void JuliaResponse::_internal_set_rgba_data(const std::string& value) {
  
  _impl_.rgba_data_.Set(value, GetArenaForAllocation());
}
inline std::string* JuliaResponse::_internal_mutable_rgba_data() {
  
  return _impl_.rgba_data_.Mutable(GetArenaForAllocation());
}
inline std::string* JuliaResponse::release_rgba_data() {
  // @@protoc_insertion_point(field_release:fractal.JuliaResponse.rgba_data)
  return _impl_.rgba_data_.Release();
}
inline void JuliaResponse::set_allocated_rgba_data(std::string* rgba_data) {
  if (rgba_data != nullptr) {
    
  } else {
    
  }
  _impl_.rgba_data_.SetAllocated(rgba_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rgba_data_.IsDefault()) {
    _impl_.rgba_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fractal.JuliaResponse.rgba_data)
}

// double calculation_time_ms = 2;
inline void JuliaResponse::clear_calculation_time_ms() {
  _impl_.calculation_time_ms_ = 0;
}
inline double JuliaResponse::_internal_calculation_time_ms() const {
  return _impl_.calculation_time_ms_;
}
inline double JuliaResponse::calculation_time_ms() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaResponse.calculation_time_ms)
  return _internal_calculation_time_ms();
}
inline void JuliaResponse::_internal_set_calculation_time_ms(double value) {
  
  _impl_.calculation_time_ms_ = value;
}
inline void JuliaResponse::set_calculation_time_ms(double value) {
  _internal_set_calculation_time_ms(value);
  // @@protoc_insertion_point(field_set:fractal.JuliaResponse.calculation_time_ms)
}

// string server_id = 3;
inline void JuliaResponse::clear_server_id() {
  _impl_.server_id_.ClearToEmpty();
}
inline const std::string& JuliaResponse::server_id() const {
  // @@protoc_insertion_point(field_get:fractal.JuliaResponse.server_id)
  return _internal_server_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JuliaResponse::set_server_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fractal.JuliaResponse.server_id)
}
inline std::string* JuliaResponse::mutable_server_id() {
  std::string* _s = _internal_mutable_server_id();
  // @@protoc_insertion_point(field_mutable:fractal.JuliaResponse.server_id)
  return _s;
}
inline const std::string& JuliaResponse::_internal_server_id() const {
  return _impl_.server_id_.Get();
}
inline void JuliaResponse::_internal_set_server_id(const std::string& value) {
  
  _impl_.server_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JuliaResponse::_internal_mutable_server_id() {
  
  return _impl_.server_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JuliaResponse::release_server_id() {
  // @@protoc_insertion_point(field_release:fractal.JuliaResponse.server_id)
  return _impl_.server_id_.Release();
}
inline void JuliaResponse::set_allocated_server_id(std::string* server_id) {
  if (server_id != nullptr) {
    
  } else {
    
  }
  _impl_.server_id_.SetAllocated(server_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_id_.IsDefault()) {
    _impl_.server_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fractal.JuliaResponse.server_id)
}

// -------------------------------------------------------------------

// ShutdownRequest

// -------------------------------------------------------------------

// ShutdownResponse

// string message = 1;
inline void ShutdownResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ShutdownResponse::message() const {
  // @@protoc_insertion_point(field_get:fractal.ShutdownResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShutdownResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fractal.ShutdownResponse.message)
}
inline std::string* ShutdownResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:fractal.ShutdownResponse.message)
  return _s;
}
inline const std::string& ShutdownResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ShutdownResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ShutdownResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* ShutdownResponse::release_message() {
  // @@protoc_insertion_point(field_release:fractal.ShutdownResponse.message)
  return _impl_.message_.Release();
}
inline void ShutdownResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fractal.ShutdownResponse.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fractal

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_fractal_2eproto
