# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fractal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fractal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfractal.proto\x12\x07\x66ractal\"\xb6\x01\n\x0cJuliaRequest\x12\x0e\n\x06\x63_real\x18\x01 \x01(\x01\x12\x0e\n\x06\x63_imag\x18\x02 \x01(\x01\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x16\n\x0emax_iterations\x18\x05 \x01(\x05\x12\x13\n\x0bpoly_degree\x18\x06 \x01(\x05\x12\r\n\x05x_min\x18\x07 \x01(\x01\x12\r\n\x05x_max\x18\x08 \x01(\x01\x12\r\n\x05y_min\x18\t \x01(\x01\x12\r\n\x05y_max\x18\n \x01(\x01\"R\n\rJuliaResponse\x12\x11\n\trgba_data\x18\x01 \x01(\x0c\x12\x1b\n\x13\x63\x61lculation_time_ms\x18\x02 \x01(\x01\x12\x11\n\tserver_id\x18\x03 \x01(\t\"\x11\n\x0fShutdownRequest\"#\n\x10ShutdownResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x92\x01\n\x0e\x46ractalService\x12?\n\x0e\x43\x61lculateJulia\x12\x15.fractal.JuliaRequest\x1a\x16.fractal.JuliaResponse\x12?\n\x08Shutdown\x12\x18.fractal.ShutdownRequest\x1a\x19.fractal.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fractal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JULIAREQUEST']._serialized_start=27
  _globals['_JULIAREQUEST']._serialized_end=209
  _globals['_JULIARESPONSE']._serialized_start=211
  _globals['_JULIARESPONSE']._serialized_end=293
  _globals['_SHUTDOWNREQUEST']._serialized_start=295
  _globals['_SHUTDOWNREQUEST']._serialized_end=312
  _globals['_SHUTDOWNRESPONSE']._serialized_start=314
  _globals['_SHUTDOWNRESPONSE']._serialized_end=349
  _globals['_FRACTALSERVICE']._serialized_start=352
  _globals['_FRACTALSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
