# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fractal_pb2 as fractal__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fractal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FractalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateJulia = channel.unary_unary(
                '/fractal.FractalService/CalculateJulia',
                request_serializer=fractal__pb2.JuliaRequest.SerializeToString,
                response_deserializer=fractal__pb2.JuliaResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/fractal.FractalService/Shutdown',
                request_serializer=fractal__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=fractal__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class FractalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateJulia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FractalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateJulia': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateJulia,
                    request_deserializer=fractal__pb2.JuliaRequest.FromString,
                    response_serializer=fractal__pb2.JuliaResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=fractal__pb2.ShutdownRequest.FromString,
                    response_serializer=fractal__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fractal.FractalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fractal.FractalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FractalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateJulia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fractal.FractalService/CalculateJulia',
            fractal__pb2.JuliaRequest.SerializeToString,
            fractal__pb2.JuliaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fractal.FractalService/Shutdown',
            fractal__pb2.ShutdownRequest.SerializeToString,
            fractal__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
